[database.server]
host = "qai-rai-beta-server.postgres.database.azure.com"
#host = "localhost"
port = 5432
dbname = "qai-rai-beta-database"
user = "dttipmwzkw"
password = "havkew-7kypDi-mopnaq"

[frontend]
host = "https://qai-rai-beta.azurewebsites.net"

[genai]
api_key = "AIzaSyDQ1SIza0-BkotiSbJKNLF_OCQ5VmH_ru0"
model = "gemini-pro"