dependencies:
  - jupyter
  - matplotlib
  - numpy
  - psycopg[binary]
  - pylint
  - git+https://github.com/tensorflow/model-card-toolkit.git
  - git+https://github.com/LukasMasuch/streamlit-pydantic.git
  - streamlit>=1.31
  - pycountry
